### ISSUE TITLE
Usersnap integration with next-js not working!

### ISSUE THREAD

**Issue by AHTHneeuhl** [usersnap/public#110]
I followed guide to integrate usersnap in next-js application but it didn't worked.

**Comment by gabberr** [comment]
Hello @AHTHneeuhl 
Sorry for the late reply. Can you add more information about the issues your have encountered?
We have just updated the example to the latest nextjs, be sure to check it out.

**Comment by m1771vw** [comment]
I'm trying out the Next.js example but it's not working. Even when I set up the example I don't see anything regarding Usersnap. I've replaced the API key. Are there any extra steps that need be taken?
