### ISSUE TITLE
Usersnap - Integration Test

### ISSUE THREAD

**Issue by hcapco** [usersnap/public#30]
**Sender**: sophia@usersnap.com
**Comment**: This example screen shows you if your integration setup is correct.

<a href='https://usersnappublic.s3.amazonaws.com/testfeedback/itworks.png'>![Usersnap - Integration Test](https://usersnappublic.s3.amazonaws.com/testfeedback/itworks.png)</a>
<a href='https://usersnappublic.s3.amazonaws.com/testfeedback/itworks.png'>Download original image</a>

**Browser**: Chrome Chrome
**Referer**: [http://www.usersnap.com](http://www.usersnap.com)
**Browser size**: 1680 x 1050

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by robertaistleitner** [comment]
@srecnig well done, thanks! 😛

**Comment by srecnig** [comment]
well, that was unexpected 🙈
