### ISSUE TITLE
Please add a Next.js Example

### ISSUE THREAD

**Issue by codeBelt** [usersnap/public#31]
Can you add an example to show the best way to add [Usersnap](https://usersnap.com/) to a [Next.js](https://nextjs.org) app.

**Comment by gabberr** [comment]
Hello @codeBelt 

Sorry for the late response. We are updating the repository  and we added a next.js example here: https://github.com/usersnap/public/tree/master/next-js

**Comment by codeBelt** [comment]
Thanks!
