### ISSUE TITLE
script.defer should be boolean attr

### ISSUE THREAD

**Issue by smlkA** [usersnap/public#41]
Hey, I have minor thing to report=)

I have just noticed following code in Global Snippet:
` script.defer = 1;`
Typescript said me that defer attr should be Boolean type.
Checked in [spec](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element): `[CEReactions] attribute boolean defer;`

Are there any reason to use number instead of Boolean true?

P.S. not sure this is the right place to report but let it be here

BR

**Comment by gabberr** [comment]
Hello!  
> Are there any reason to use number instead of Boolean true?
Good question. You can change that to true. 
The reason is `1` is shorter to type than `true`. 
They are both truthy.
